### PR TITLE
Fixed Label color transparent not being applied

### LINKED ISSUE #60: Label transparent background
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: `1.0.0`
 - Android version: `8.0.0`

#### Steps to reproduce:

The contrast between the label text color and the overlay color is enough for my use case, so I would like to have a completely transparent label background (or not background at all).

However, when I set `android.R.color.transparent` with `.setLabelBackgroundColor()` the default background seems to be set.

Also, because there's no access to the underlying `List<FabWithLabelView>` from `SpeedDialView` or `SpeedDialActionItem`, I can not perform further customizations.

#### Observed Results:

  * Action item label background IS NOT transparent
  

#### Expected Results:

  * Action item label background IS transparent

#### Relevant Code:

```kotlin
val colorTransparent = ContextCompat.getColor(this, android.R.color.transparent)
val colorWhite = ContextCompat.getColor(this, android.R.color.white)

val fabMenuAddCreditCard = SpeedDialActionItem.Builder(R.id.some_id,  R.drawable.some_drawable)
    .setLabel(getString(R.string.some_string))
    .setLabelColor(colorWhite)
    .setLabelBackgroundColor(colorTransparent)
    .create()
```

screen shot 2018-06-07 at 12 29 52 pm

When I used a slightly similar color 

`<color name="transparent2">#00000001</color>`

```kotlin
val colorTransparent = ContextCompat.getColor(this, R.color.transparent2)

val fabMenuAddCreditCard = SpeedDialActionItem.Builder(R.id.some_id,  R.drawable.some_drawable)
    .setLabel(getString(R.string.some_string))
    .setLabelColor(colorWhite)
    .setLabelBackgroundColor(colorTransparent)
    .create()
```

screen shot 2018-06-07 at 12 35 36 pm

### PR DESCRIPTION
**Pull request by leinardi**
Fixes #60

### CODE REVIEW

File: library/src/main/java/com/leinardi/android/speeddial/FabWithLabelView.java [hunk 1]
```diff
@@ -344,7 +349,33 @@ private void setLabelColor(@ColorInt int color) {
...
+                if (mLabelCardViewElevation != 0) {
+                    mLabelCardView.setElevation(mLabelCardViewElevation);
+                    mLabelCardViewElevation = 0;
+                }
+            } else {
+                if (mLabelCardViewBackground != null) {
+                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
+                        mLabelCardView.setBackground(mLabelCardViewBackground);
+                    } else {
+                        mLabelCardView.setBackgroundDrawable(mLabelCardViewBackground);
```
Comment (leinardi) [inline library/src/main/java/com/leinardi/android/speeddial/FabWithLabelView.java:373]: **Reporter**: Error Prone
**Rule**: deprecation
**Severity**: WARN
**File**: library/src/main/java/com/leinardi/android/speeddial/FabWithLabelView.java L373

setBackgroundDrawable(Drawable) in View has been deprecated

mLabelCardView.setBackgroundDrawable(mLabelCardViewBackground);^

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<1965684139>*

Comment (leinardi) [inline library/src/main/java/com/leinardi/android/speeddial/FabWithLabelView.java:373]: **Reporter**: Error Prone
**Rule**: deprecation
**Severity**: WARN
**File**: library/src/main/java/com/leinardi/android/speeddial/FabWithLabelView.java L373

setBackgroundDrawable(Drawable) in View has been deprecated

mLabelCardView.setBackgroundDrawable(mLabelCardViewBackground);^

*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<1965684139>*
