### PR TITLE
Closes #80: Making dynamic changes of Action Items easier

### LINKED ISSUE #80: Dynamic Theming of SpeedDialActionItem(s)
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the library.

### Step 2: Describe your environment
 - Library version: `1.0.2`

#### Steps to reproduce:

  1. set up the library
  2. create a set of menus
  3. attempt to theme them dynamically

#### Observed Results:

  * after creating action items (through a Builder class), there is no way to change their colors/theme of SpeedDialActionItems without removing and re-creating all of the menu items individually, which is inefficient and annoying and dumb and I don't want to do it please provide some option other than this I really don't want to do this thanks
  

#### Expected Results:

  * methods to change attributes of individual FABs after they have been created would be very useful
  * my specific use case is a setting that changes the 'theme' of my application without restarting it
  * it also has a day/night theme that refreshes itself in onResume
  * I can see that the views are completely separated from the SpeedDialActionItem class, possibly to allow some sort of view recycling or some other organizational benefit, but if this change is made, then the Builder class will serve to do nothing but complicate implementation for no reason, and I would recommend removing it entirely and having users construct SpeedDialActionItems themselves.

#### Relevant Code:

There is quite a bit, but nothing especially useful.
Here is a link to [SpeedDialActionItem.java](https://github.com/leinardi/FloatingActionButtonSpeedDial/blob/master/library/src/main/java/com/leinardi/android/speeddial/SpeedDialActionItem.java) if it makes your life easier.

I am currently using Jahir's abandoned [FABsMenu](https://github.com/jahirfiquitiva/FABsMenu) library, so there is not a huge amount of urgency for this to be completed at the moment, but I would like to migrate to this one before the lack of support becomes an issue. If I have the time, I may simply fix this myself and create a PR, but that will likely not happen for another week or two.

Thank you for creating and maintaining this project. Apart from this one issue it is very nice, has a lot more functionality than one would expect from a row of buttons (option for inflating a menu resource is good), and the animations are completely flawless.

### PR DESCRIPTION
**Pull request by leinardi**

### CODE REVIEW

File: sample/src/main/java/com/leinardi/android/speeddial/sample/MainActivity.java [hunk 1]
```diff
@@ -55,16 +56,21 @@ private void initSpeedDial(boolean addActionItems) {
...
-                    .setFabImageTintColor(ResourcesCompat.getColor(getResources(), R.color.inbox_primary, getTheme()))
-                    .setLabel(R.string.label_custom_color)
-                    .setLabelColor(Color.WHITE)
-                    .setLabelBackgroundColor(ResourcesCompat.getColor(getResources(), R.color.inbox_primary,
-                            getTheme()))
-                    .create());
+                Drawable drawable = AppCompatResources.getDrawable(MainActivity.this, R.drawable.ic_custom_color);
+                FabWithLabelView fabWithLabelView = mSpeedDialView.addActionItem(new SpeedDialActionItem.Builder(R.id
+                        .fab_custom_color, drawable)
+                        .setFabImageTintColor(ResourcesCompat.getColor(getResources(), R.color.inbox_primary, getTheme()))
```
Comment (leinardi) [inline sample/src/main/java/com/leinardi/android/speeddial/sample/MainActivity.java]: **Reporter**: Checkstyle
**Rule**: com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck
**Severity**: ERROR
**File**: /home/travis/build/leinardi/FloatingActionButtonSpeedDial/sample/src/main/java/com/leinardi/android/speeddial/sample/MainActivity.java L62

Line is longer than 120 characters (found 122).


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-810533692>*
